[package]
name = "bf-interpreter"
version = "0.1.0"
edition = "2021"

[lib]
name = "bf_interpreter"
path = "src/lib.rs"

[[bin]]
name = "bf-interpreter"
path = "src/main.rs"

[dependencies]
bf-core = { path = "../bf-core" }
cranelift-codegen = { version = "0.113", optional = true }
cranelift-frontend = { version = "0.113", optional = true }
cranelift-jit = { version = "0.113", optional = true }
cranelift-module = { version = "0.113", optional = true }

[features]
jit = ["dep:cranelift-jit", "dep:cranelift-module", "dep:cranelift-codegen", "dep:cranelift-frontend"]
